// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-sections/AuroraWaves.tsx": () => import("../components/mockups/hero-sections/AuroraWaves.tsx"),
  "./components/mockups/hero-sections/BrutalistMono.tsx": () => import("../components/mockups/hero-sections/BrutalistMono.tsx"),
  "./components/mockups/hero-sections/DarkCinematic.tsx": () => import("../components/mockups/hero-sections/DarkCinematic.tsx"),
  "./components/mockups/hero-sections/GradientFlow.tsx": () => import("../components/mockups/hero-sections/GradientFlow.tsx"),
  "./components/mockups/hero-sections/InteractiveCards.tsx": () => import("../components/mockups/hero-sections/InteractiveCards.tsx"),
  "./components/mockups/hero-sections/MeshGradient.tsx": () => import("../components/mockups/hero-sections/MeshGradient.tsx"),
  "./components/mockups/hero-sections/OrbitalMotion.tsx": () => import("../components/mockups/hero-sections/OrbitalMotion.tsx"),
  "./components/mockups/hero-sections/ParticleGrid.tsx": () => import("../components/mockups/hero-sections/ParticleGrid.tsx"),
  "./components/mockups/hero-sections/PlanBuilder.tsx": () => import("../components/mockups/hero-sections/PlanBuilder.tsx"),
  "./components/mockups/hero-sections/SplitReveal.tsx": () => import("../components/mockups/hero-sections/SplitReveal.tsx"),
  "./components/mockups/hero-sections/SplitRevealPro.tsx": () => import("../components/mockups/hero-sections/SplitRevealPro.tsx"),
  "./components/mockups/hero-sections/TypographicBold.tsx": () => import("../components/mockups/hero-sections/TypographicBold.tsx")
};
